[
	["TERRITORY_AIRPORT_A", "Airport A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_AIRPORT_A", "", 0, ""],
	["TERRITORY_AIRPORT_B", "Airport B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_AIRPORT_B", "", 0, ""],
	["TERRITORY_AIRPORT_C", "Airport C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_AIRPORT_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]