[
	["TERRITORY_BLANCHES_A", "Blanches A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_BLANCHES_A", "", 0, ""],
	["TERRITORY_BLANCHES_B", "Blanches B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_BLANCHES_B", "", 0, ""],
	["TERRITORY_BLANCHES_C", "Blanches C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_BLANCHES_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]