[
	["TERRITORY_DOURDAN_A", "Dourdan A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_DOURDAN_A", "", 0, ""],
	["TERRITORY_DOURDAN_B", "Dourdan B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_DOURDAN_B", "", 0, ""],
	["TERRITORY_DOURDAN_C", "Dourdan C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_DOURDAN_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]