[
	["TERRITORY_LA_PESSAGNE_A", "La Pessagne A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_PESSAGNE_A", "", 0, ""],
	["TERRITORY_LA_PESSAGNE_B", "La Pessagne B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_PESSAGNE_B", "", 0, ""],
	["TERRITORY_LA_PESSAGNE_C", "La Pessagne C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_PESSAGNE_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]