[
	["TERRITORY_LARCHE_A", "Larche A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LARCHE_A", "", 0, ""],
	["TERRITORY_LARCHE_B", "Larche B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LARCHE_B", "", 0, ""],
	["TERRITORY_LARCHE_C", "Larche C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LARCHE_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]