[
	["TERRITORY_LA_RIVIERE_A", "La Riviere A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_RIVIERE_A", "", 0, ""],
	["TERRITORY_LA_RIVIERE_B", "La Riviere B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_RIVIERE_B", "", 0, ""],
	["TERRITORY_LA_RIVIERE_C", "La Riviere C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_RIVIERE_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]