[
	["TERRITORY_LA_TRINITE_A", "La Trinite A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_TRINITE_A", "", 0, ""],
	["TERRITORY_LA_TRINITE_B", "La Trinite B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_TRINITE_B", "", 0, ""],
	["TERRITORY_LA_TRINITE_C", "La Trinite C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LA_TRINITE_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]