[
	["TERRITORY_LE_PORT_A", "Le Port A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LE_PORT_A", "", 0, ""],
	["TERRITORY_LE_PORT_B", "Le Port B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LE_PORT_B", "", 0, ""],
	["TERRITORY_LE_PORT_C", "Le Port C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_LE_PORT_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]