[
	["TERRITORY_MILITARY_BASE_A", "Military Base A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_MILITARY_BASE_A", "", 0, ""],
	["TERRITORY_MILITARY_BASE_B", "Military Base B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_MILITARY_BASE_B", "", 0, ""],
	["TERRITORY_MILITARY_BASE_C", "Military Base C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_MILITARY_BASE_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]