[
	["TERRITORY_MORAY_A", "Moray A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_MORAY_A", "", 0, ""],
	["TERRITORY_MORAY_B", "Moray B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_MORAY_B", "", 0, ""],
	["TERRITORY_MORAY_C", "Moray C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_MORAY_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]