[
	["TERRITORY_SAINT_LOUIS_A", "Saint Louis A", 5000, "AIRBASE"],
	["TERRITORY_FLAG_SAINT_LOUIS_A", "", 0, ""],
	["TERRITORY_SAINT_LOUIS_B", "Saint Louis B", 5000, "AIRBASE"],
	["TERRITORY_FLAG_SAINT_LOUIS_B", "", 0, ""],
	["TERRITORY_SAINT_LOUIS_C", "Saint Louis C", 5000, "AIRBASE"],
	["TERRITORY_FLAG_SAINT_LOUIS_C", "", 0, ""],
	["TERRITORY_MONTAIN_MILITARY_BASE", "Montain Military Base", 5000, "MILITARY"],
	["TERRITORY_FLAG_MMB", "", 0, ""]
]